[package]
name = "cfg-specialize"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"

[workspace]

[dependencies]
cfg-specialize-macros = { path = "cfg-specialize-macros" }
