[package]
name = "cfg-specialize"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[workspace]

[dependencies]
cfg-specialize-macros = { path = "cfg-specialize-macros" }

[dev-dependencies]
stdsimd = { path = "../stdsimd" }

[target.'cfg(target_arch = "x86")'.dependencies]
cupid = "0.3"
[target.'cfg(target_arch = "x86_64")'.dependencies]
cupid = "0.3"
