[package]
name = "cfg-specialize"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]

[workspace]

[dependencies]
cfg-specialize-macros = { path = "cfg-specialize-macros" }

[dev-dependencies]
stdsimd = { git = 'https://github.com/rust-lang-nursery/stdsimd' }
